### ISSUE TITLE
About Us page - Contact Us in About us page is not clickable and it does not show any contact details.

### ISSUE THREAD

**Issue by vidyavenkatesh82** [getshravan/synapsecovidhomecare#8]
![image](https://user-images.githubusercontent.com/79722840/117056994-c8af3500-acd1-11eb-8ecb-c5f811d558cc.png)

**Comment by getshravan** [comment]
I don't think `Contact Us` is required here. I have removed it.

**Comment by vidyavenkatesh82** [comment]
Working fine. I see no contact us page in About Us screen.
